// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function ConvertImageFormat(arg1:string,arg2:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<main.FileData>;

export function ReadConfigFile():Promise<config.ImageConfig|string>;

export function ReadFiles():Promise<string>;

export function UpdateConfigFile(arg1:string,arg2:string):Promise<string>;
