// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertImageFormat(arg1, arg2) {
  return window['go']['main']['App']['ConvertImageFormat'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadConfigFile() {
  return window['go']['main']['App']['ReadConfigFile']();
}

export function ReadFiles() {
  return window['go']['main']['App']['ReadFiles']();
}

export function UpdateConfigFile(arg1, arg2) {
  return window['go']['main']['App']['UpdateConfigFile'](arg1, arg2);
}
